server:
    port: 8080

spring:
    application:
        name: api-service
    datasource:
        password: 123456
        url: jdbc:postgresql://localhost:5431/postgres
        username: postgres
    jackson:
        serialization:
            indent_output: true
    jpa:
        hibernate:
            ddl-auto: none
            show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    flyway:
        baseline-on-migrate: true
springdoc:
    swagger-ui:
        path: /swagger-ui.html
eureka:
    client:
        fetch-registry: true

logging:
    level:
        com:
            example:
                eshop: TRACE
        org:
            hibernate:
                engine:
                    jdbc:
                        env:
                            internal:
                                LobCreatorBuilderIpml: error
            springframework:
                jdbc:
                    datasource:
                        init:
                            ScriptUtils: debug
management:
    endpoints:
        web:
            exposure:
                include: '*'
